# adapted from https://gitlab.matthewrease.net/matthew/ways

docker-build-self:
  image: docker:cli
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        docker build --pull --build-arg VERSION="$CI_COMMIT_TAG" -t "$DOCKER_IMAGE_NAME" .
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
        docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker build --pull --build-arg VERSION="commit-$CI_COMMIT_SHORT_SHA" -t "$DOCKER_IMAGE_NAME" .
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_SERVER_HOST == "gitlab.matthewrease.net"'
      exists:
        - Dockerfile
      when: always
    - if: '$CI_COMMIT_TAG && $CI_SERVER_HOST == "gitlab.matthewrease.net"'
      exists:
        - Dockerfile
      when: always
    - when: never
  tags:
    - docker

docker-build-gitlab:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
        docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_SERVER_HOST == "gitlab.com"'
      exists:
        - Dockerfile
      when: always
    - if: '$CI_COMMIT_TAG && $CI_SERVER_HOST == "gitlab.com"'
      exists:
        - Dockerfile
      when: always
    - when: never

deploy-solasbot:
  stage: deploy
  environment:
    name: production
  before_script:
    - chmod 600 "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -i "$SSH_PRIVATE_KEY" "$SSH_USER@$SSH_HOST" "deploy $CI_COMMIT_TAG"
  rules:
    # Major (breaking) update
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.0$/ && $CI_SERVER_HOST == "gitlab.matthewrease.net"'
      when: manual
    # Minor update
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+$/ && $CI_SERVER_HOST == "gitlab.matthewrease.net"'
      when: always
    - when: never
